server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway    # ← ADD THIS
  endpoint:
    gateway:
      enabled: true 